IATI/iatipublisher

- README.md
- app/Providers/AppServiceProvider.php
- public/js/app.js
> Review: 58-update-readmemd

- .github/workflows/deployment-prod.yml
- .github/workflows/deployment-staging.yml
> Resolve: 68-devops-fix : Staging and Production seperate deployment fix

- .github/workflows/deployment-prod.yml
- .github/workflows/deployment-staging.yml
[x] fix issue with variable name and npm package of caprover
[x] fix deploy name
> Resolve 68-devops-caprover-deploy: fix issue with caprover vulnerability and used npm package for deployment

- Dockerfile
> add migrate and seed in dockerfile

- app/Providers/AppServiceProvider.php
> Resolve 68: https-scheme-fix

- app/Http/Controllers/Auth/RegisterController.php
- public/js/script.js
- tests/Feature/AuthenticationTest.php
> test-with-staging

- .github/workflows/deployment-prod.yml
> Review: 145-Deployment-Action-Fix

- app/Http/Controllers/Auth/RegisterController.php
- public/js/script.js
- tests/Feature/RegisterTest.php
> Draft: 112-bug-fixes

- packages/main.yaml
> 68-image-fix

- app/Http/Requests/Activity/ActivityBaseRequest.php
- app/Http/Requests/Activity/ContactInfo/ContactInfoRequest.php
- app/IATI/Data/elementJsonSchema.json
> Draft: 59-activity-complex-forms

- app/Http/Controllers/Admin/Activity/RelatedActivityController.php
- app/IATI/Services/Activity/RelatedActivityService.php
> Draft: 60-activity-transaction-detail-page-new

- app/Http/Controllers/Admin/Activity/TransactionController.php
> 60-activity-transaction-detail-page-new

- resources/views/admin/activity/date/edit.blade.php
form error shown on top of activity date
> Draft: 60-activity-transaction-detail-page

- app/Http/Middleware/RedirectActivity.php
> Draft: 331-result-element-of-activity

- app/Http/Controllers/Admin/Activity/DateController.php
> 377-fixing-bugs

- .github/workflows/deployment-prod.yml
- Dockerfile
> 446-devops-fix

- public/mix-manifest.json
- resources/assets/js/views/web/partials/SignIn.vue
> 138-error-messages

- app/Helpers/general.php
- app/IATI/Data/elementJsonSchema.json
- app/IATI/Data/organizationElementJsonSchema.json
- app/IATI/Elements/Forms/WrapperCollection.php
- app/IATI/Elements/Forms/WrapperCollectionForm.php
- public/mix-manifest.json
- resources/assets/js/views/organisation/OrganisationData.vue
- resources/views/admin/activity/partial/form-title.blade.php
- resources/views/admin/organisation/forms/documentLink/documentLink.blade.php
- resources/views/admin/organisation/forms/name/name.blade.php
- resources/views/admin/organisation/forms/organisationIdentifier/edit.blade.php
- resources/views/admin/organisation/forms/recipientCountryBudget/recipientCountryBudget.blade.php
- resources/views/admin/organisation/forms/recipientOrgBudget/recipientOrgBudget.blade.php
- resources/views/admin/organisation/forms/recipientRegionBudget/recipientRegionBudget.blade.php
- resources/views/admin/organisation/forms/reportingOrg/reportingOrg.blade.php
- resources/views/admin/organisation/forms/totalBudget/totalBudget.blade.php
- resources/views/admin/organisation/forms/totalExpenditure/totalExpenditure.blade.php
- resources/views/admin/organisation/partial/form-title.blade.php
organization and complete status fixes
> 471-organization-activity-element-status

- resources/views/admin/layouts/app.blade.php
- resources/views/layouts/app.blade.php
- resources/views/web/layouts/app.blade.php
> frontend-fixes

- app/Http/Controllers/Admin/ImportActivity/ImportActivityController.php
> 423-csv-xml-upload-no-org-id

- app/Http/Controllers/Auth/VerificationController.php
- app/Http/Requests/Activity/PolicyMarker/PolicyMarkerRequest.php
- app/IATI/Data/elementJsonSchema.json
- app/IATI/Services/ElementCompleteService.php
- app/Observers/ActivityObserver.php
- app/Providers/EventServiceProvider.php
- public/mix-manifest.json
- tests/Feature/Element/PlannedDisbursementTest.php
> Draft: 719-activity-reporting-org

- app/IATI/Services/User/UserService.php
> 743-new-user-registration-in-iati

- app/Http/Controllers/Auth/IatiRegisterController.php
- app/IATI/Services/User/UserService.php
- public/mix-manifest.json
- resources/assets/js/views/web/IatiRegisterPage.vue
- routes/web.php
> - [x] route issue fixed

- packages/development/ingress.yaml
- packages/production/ingress.yaml
- packages/staging/ingress.yaml
> 403 Forbidden issue resolve

- app/CsvImporter/Entities/Activity/Components/Elements/Budget.php
- app/CsvImporter/Entities/Activity/Components/Elements/Location.php
- app/CsvImporter/Entities/Activity/Components/Elements/PlannedDisbursement.php
- app/CsvImporter/Entities/Activity/Components/Elements/RelatedActivity.php
- app/CsvImporter/Entities/Activity/Components/Elements/Tag.php
- app/Observers/ActivityObserver.php
- public/mix-manifest.json
- resources/assets/js/views/activity/elements/PlannedDisbursement.vue
- resources/assets/js/views/activity/elements/Tag.vue
> 709-import-csv-fixes

- app/Http/Controllers/Admin/ImportActivity/ImportActivityController.php
- app/IATI/Services/ImportActivity/ImportCsvService.php
- app/IATI/Services/ImportActivity/ImportXmlService.php
- app/XmlImporter/Foundation/XmlQueueProcessor.php
- public/mix-manifest.json
- resources/assets/js/views/import/ImportList.vue
> 786-limit-axios-call

- app/Helpers/general.php
- app/Http/Controllers/Admin/ImportActivity/ImportActivityController.php
- app/Http/Requests/Activity/UploadActivity/ImportActivityRequest.php
- app/IATI/Services/ElementCompleteService.php
- app/IATI/Services/ImportActivity/ImportCsvService.php
- app/XmlImporter/Foundation/Mapper/Components/Activity.php
- app/XmlImporter/Foundation/Mapper/Components/Elements/Result.php
- app/XmlImporter/Foundation/Support/Factory/XmlValidator.php
- app/XmlImporter/Foundation/Support/Providers/XmlServiceProvider.php
- app/XmlImporter/Foundation/XmlQueueProcessor.php
- public/mix-manifest.json
- resources/assets/js/components/ToastMessage.vue
- resources/assets/js/views/activity/results/ResultDetail.vue
- resources/assets/js/views/import/ActivityUpload.vue
> Review: 753-import-fixes

- app/Http/Controllers/Admin/ImportActivity/ImportActivityController.php
- app/IATI/Services/ImportActivity/ImportCsvService.php
- app/IATI/Services/ImportActivity/ImportXmlService.php
- app/XmlImporter/Foundation/XmlQueueProcessor.php
- public/mix-manifest.json
- resources/assets/js/views/import/ImportList.vue
> Resolved: 786-limit-axios-call

- public/mix-manifest.json
- resources/assets/js/components/ErrorMessage.vue
- resources/assets/js/views/web/RegisterPage.vue
- resources/assets/js/views/web/partials/AdminFooter.vue
- resources/assets/js/views/web/partials/JoinNow.vue
- resources/assets/js/views/web/partials/WebFooter.vue
> iati-support-email-updated

- public/mix-manifest.json
- resources/assets/js/views/web/partials/AdminFooter.vue
- resources/assets/js/views/web/partials/WebFooter.vue
> youtube-twitter-hyperlink

- database/seeders/RoleTableSeeder.php
> Resolved: production-seeder-fixes

- app/IATI/Models/Activity/Activity.php
- app/IATI/Models/Activity/Indicator.php
- app/IATI/Models/Activity/Period.php
- app/IATI/Models/Activity/Result.php
- app/IATI/Models/Activity/Transaction.php
- app/IATI/Models/Organization/Organization.php
- app/IATI/Models/Setting/Setting.php
- app/IATI/Models/User/User.php
- composer.json
- composer.lock
- config/app.php
- config/audit.php
- config/debugbar.php
- config/excel.php
- database/migrations/2023_01_11_100340_create_audits_table.php
- auditable in models
- events like create, update, delete are audited
> Base for audit

- app/IATI/Data/elementJsonSchema.json
> Resolve: user-manual-hover-text-update

- resources/views/admin/layouts/app.blade.php
- resources/views/web/layouts/app.blade.php
google analytics for production only
> Resolve : gtag-production-only

- package-lock.json
- package.json
- public/mix-manifest.json
> 999-remove-unnecessary-node-package

- README.md
> Reviewed: 966-readme-update

- app/IATI/Elements/Xml/OrganizationXmlGenerator.php
> Review: organization-xml-fix

- app/IATI/Elements/Xml/OrganizationXmlGenerator.php
- app/IATI/Services/Organization/RecipientCountryBudgetService.php
- app/IATI/Services/Organization/RecipientOrgBudgetService.php
> Resolved: organization-xml-sequence-fixed

- app/IATI/Repositories/Activity/ActivityRepository.php
- app/IATI/Services/User/UserService.php
- public/mix-manifest.json
- resources/assets/js/views/web/IatiRegisterPage.vue
- resources/assets/js/views/web/RegisterPage.vue
> Resolved: 1024-bugs-related-with-activity

- packages/base/fpm/deployment.yaml
- packages/development/kustomization.yaml
- packages/development/pvc.yaml
- packages/production/kustomization.yaml
- packages/production/pvc.yaml
- packages/staging/kustomization.yaml
- packages/staging/pvc.yaml
> Fix Persistence Volume

- app/IATI/Services/ElementCompleteService.php
- app/IATI/Services/OrganizationElementCompleteService.php
- app/IATI/Traits/ElementCompleteServiceTrait.php
> ElementCompleteService Refactored

- app/IATI/Services/ElementCompleteService.php
- app/IATI/Services/OrganizationElementCompleteService.php
- app/IATI/Traits/ElementCompleteServiceTrait.php
> Reviewed: Refactor ElementCompleteService

- app/Http/Controllers/Admin/Workflow/BulkPublishingController.php
- app/IATI/Repositories/Activity/BulkPublishingStatusRepository.php
- app/IATI/Services/Activity/BulkPublishingStatusService.php
- app/IATI/Services/Workflow/BulkPublishingService.php
- app/Jobs/BulkPublishActivities.php
- config/horizon.php
- resources/assets/js/components/BulkPublishingErrorPopup.vue
- resources/assets/js/views/activity/bulk-publish/PublishSelected.vue
- resources/assets/js/views/activity/partials/PageTitle.vue
- routes/publish.php
[x] Show confirmation popup to stop bulk publish
[x] Previous bulk publish cancels on button click
> Bulk Publishing Cancellation 

- packages/development/config.yaml
- packages/staging/config.yaml
> Resolved: db-port-change

- config/database.php
> Resolved: database-config-updated

- app/Providers/ExtendedMailServiceProvider.php
- config/app.php
> Review: 1030-disable-email-on-local-env

- app/Providers/ExtendedMailServiceProvider.php
> Review: 1030-enable-email-for-staging

- app/Http/Requests/Activity/ActivityBaseRequest.php
- app/Http/Requests/Activity/Sector/SectorRequest.php
- app/IATI/Services/Activity/TransactionService.php
- app/IATI/Services/Workflow/ActivityWorkflowService.php
- app/Observers/TransactionObserver.php
> 	Review: Ensured percentage of same vocabulary is equal to 100%

- app/Http/Requests/Activity/Budget/BudgetRequest.php
- app/IATI/Services/Activity/ActivityDefaultService.php
- app/IATI/Services/Activity/ActivityService.php
> 	Review: completeness of budget element if budget-not-provided is used

- public/mix-manifest.json
- resources/assets/js/components/buttons/PublishButton.vue
- resources/assets/js/views/activity/bulk-publish/ValidationErrors.vue
> Review: Publish flow fixes

- .github/workflows/production-workflow.yml
- Dockerfile.production
> Reviewed: dockerfile-production-fix

- app/Http/Requests/Activity/Transaction/TransactionRequest.php
- app/IATI/Data/elementJsonSchema.json
-[x] added information in value help text
> 	Review: 1069-adding-negative-value-in-transaction

- app/CsvImporter/Entities/Activity/Components/ActivityRow.php
- app/Http/Requests/Activity/Transaction/TransactionRequest.php
- app/IATI/Repositories/Activity/TransactionRepository.php
- app/IATI/Services/Activity/TransactionService.php
- app/XmlImporter/Foundation/Support/Factory/Validation.php
- app/XmlImporter/Foundation/Support/Factory/XmlValidator.php
- app/XmlImporter/Foundation/XmlQueueWriter.php
> 	Review: 1085-remove-transaction-reference-uniqueness

- app/Helpers/general.php
- app/Http/Controllers/Admin/Activity/ActivityController.php
- app/Http/Requests/Activity/RecipientCountry/RecipientCountryRequest.php
- app/Http/Requests/Activity/RecipientRegion/RecipientRegionRequest.php
- app/IATI/Models/Activity/Activity.php
- app/IATI/Services/Activity/TransactionService.php
- app/IATI/Services/ElementCompleteService.php
- app/Observers/TransactionObserver.php
…leted
-[x] fix: complete status preserved if region 100% and country is deleted
-[x] fix: updated validation message
-[x] fix: recipient region and recipient country complete status if mentioned in transaction
> 	Reviewed: 1097-recipient-region-recipient-country-rules-feedback

- app/Data/Organization/OrganizationRegistrationAgency.json
- app/Http/Controllers/Auth/IatiRegisterController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Requests/Activity/Title/TitleRequest.php
- app/Http/Requests/Activity/UploadActivity/ImportActivityRequest.php
- app/XmlImporter/Foundation/Support/Factory/XmlValidator.php
- app/XmlImporter/Foundation/Support/Helpers/Traits/XmlHelper.php
- public/mix-manifest.json
- resources/assets/js/views/activity/ActivityDetail.vue
> Reviewed: 1110-issues-with-title

- app/Console/Commands/CompleteStatusPercentageCommand.php
- app/Http/Controllers/Admin/Activity/ActivityController.php
- app/Http/Controllers/Auth/IatiRegisterController.php
- app/Http/Controllers/Auth/LoginController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Requests/Activity/RecipientCountry/RecipientCountryRequest.php
- app/Http/Requests/Activity/RecipientRegion/RecipientRegionRequest.php
- app/Http/Requests/User/UserProfileRequest.php
- app/Http/Requests/User/UserRequest.php
- app/Http/Requests/User/UserUpdateRequest.php
- app/IATI/Models/Activity/Activity.php
- app/IATI/Models/User/User.php
- app/IATI/Services/ElementCompleteService.php
- app/Observers/ActivityObserver.php
- app/Observers/ResultObserver.php
- app/Observers/TransactionObserver.php
- database/migrations/2023_04_25_043516_add_last_logged_in_to_users_table.php
- database/migrations/2023_04_26_043516_add_complete_percentage_to_activities_table.php
- public/mix-manifest.json
- resources/assets/js/composable/title.ts
- resources/assets/js/views/activity/ActivityDetail.vue
- resources/assets/js/views/activity/indicators/IndicatorDetail.vue
- resources/assets/js/views/activity/partials/TableLayout.vue
- resources/assets/js/views/activity/periods/PeriodsDetail.vue
- resources/assets/js/views/activity/results/ResultDetail.vue
- resources/assets/js/views/activity/transactions/TransactionDetail.vue
> Resolved : 1185-dashboard-data

- app/Console/Commands/FixRegionIssues.php
- app/IATI/Traits/MigrateOrganizationTrait.php
-[x] Fixed status missing in recipient country
-[x] Fixed status missing in recipient region
> Review: 1196-issue-from-migration-region

- app/Console/Commands/FixDocumentLink.php
- app/Console/Commands/FixHumanitarian.php
- app/Console/Commands/FixRegionIssues.php
This PR fixes issue #1196  task 4 and 5
> Resolved: 1196-humanitarian-issue-fix

- app/Data/Organization/OrganizationRegistrationAgency.json
> Reviewed : 1215-new-organization-registration-agency

- app/Http/Requests/Activity/ActivityBaseRequest.php
- app/Http/Requests/Activity/Budget/BudgetRequest.php
- app/Http/Requests/Activity/PlannedDisbursement/PlannedDisbursementRequest.php
- app/Http/Requests/Organization/OrganizationBaseRequest.php
- app/Http/Requests/Organization/RecipientCountryBudget/RecipientCountryBudgetRequest.php
- tests/Unit/Csv/BudgetCsvTest.php
- tests/Unit/Csv/PlannedDisbursementCsvTest.php
- tests/Unit/Xml/BudgetXmlTest.php
- tests/Unit/Xml/PlannedDisbursementXmlTest.php
> Reviewed : 1234-budget-value-date-validation

- app/Console/Commands/FixPublishedXmlsForIssue1363Changes.php
- app/Helpers/general.php
- app/Http/Controllers/Admin/Workflow/BulkPublishingController.php
- app/IATI/Elements/Xml/XmlGenerator.php
- storage/test.xml
fix bug: Transaction not included in activity xml
fix: change the XML file of the published activities and republish them with same published date rather than current date. Test remaining
> Review: 1363-iati-publisher-not-publishing-transactions-to-activity-file-xml

- app/Console/Commands/FetchOrganisationRegistrationAgency.php
fix cache disappearing after 00:00:00UTC + 8hrs
> Review: 1342-explicit-cache-lifespan

- app/IATI/Traits/MigrateActivityTrait.php
- present_organization_identifier and iati_identifier_text in iati_identifier column
- has_ever_been_published column value
> Review: update-migration-script-for-1343-changes

- public/AppData/Data/Organization/OrganizationRegistrationAgency.json
> Review: update-static-organization-data

- app/Console/Commands/FetchOrganisationRegistrationAgency.php
- public/AppData/Data/Organization/OrganizationRegistrationAgency.json
- Update OrganizationRegistrationAgency.json
> Review: immediate-fix-for-sz-cit

- app/IATI/Repositories/User/UserRepository.php
- public/js/vendor.js.LICENSE.txt
- public/mix-manifest.json
- resources/assets/js/components/BulkpublishWithXls.vue
- resources/assets/js/components/XlsUploadIndicator.vue
- resources/assets/js/views/user/UserListing.vue
- resources/views/admin/user/index.blade.php
> Review: 1411-display-all-users-on-users-page-including-the-active-user

- app/Console/Commands/Issue1419FillFullnameAndEmailInAuditLog.php
- app/Console/Commands/Issue1419HardDeleteSoftDeletedUsers.php
- app/Http/Controllers/Admin/User/UserController.php
- app/Http/Controllers/Auth/IatiRegisterController.php
- app/IATI/Models/Audit/Audit.php
- app/IATI/Models/Organization/Organization.php
- app/IATI/Models/User/User.php
- app/IATI/Services/Audit/AuditService.php
- app/IATI/Traits/MigrateUserTrait.php
- database/migrations/2024_04_10_115935_add_full_name_and_email_to_audits_table.php
- database/migrations/2024_04_10_116000_add_nullable_to_created_by_on_activities_table.php
- database/migrations/2024_04_11_044411_remove_cascasde_on_delete_to_updated_by_on_activities_table.php
- database/migrations/2024_04_11_044411_remove_cascasde_on_delete_to_updated_by_on_organizations_table.php
- database/migrations/2024_04_11_044411_remove_cascasde_on_delete_to_updated_by_on_users_table.php
> Review: 1419-unable-to-re-add-a-user-to-iati-publisher-after-deletion

- app/Console/Commands/Issue1419FillFullnameAndEmailInAuditLog.php
- resources/assets/sass/component/_input.scss
-[x] Avoid memory error when using command.
> Review: 1419-change-command 

- resources/assets/js/views/web/WelcomePage.vue
- resources/assets/js/views/web/partials/JoinNow.vue
- resources/assets/js/views/web/partials/SignIn.vue
- resources/assets/sass/component/_input.scss
> Review: 1464-make-it-clearer-that-new-users-of-existing-iati-publisher-organisations-cannot-register-via-join-now

- app/IATI/Services/User/UserService.php
- public/mix-manifest.json
- resources/assets/sass/component/_input.scss
> Review: 1499-unable-to-register-new-organisation-on-iati-publisher-staging-site

- app/Http/Controllers/Auth/IatiRegisterController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Requests/User/UserProfileRequest.php
- app/Http/Requests/User/UserRequest.php
- app/Http/Requests/User/UserUpdateRequest.php
- app/Http/Requests/Web/IatiRegister/IatiRegisterFormRequest.php
> Review: 1507-when-user-tried-to-create-an-account-the-user-is-blocked-saying-user-already-exist

- app/XlsImporter/Foundation/Mapper/Activity.php
- resources/assets/sass/component/_input.scss
> Review: 1519-uploading-activities-via-xls-file-in-staging-of-iati-publisher-is-failing

- app/IATI/Data/elementJsonSchema.json
- app/IATI/Data/organizationElementJsonSchema.json
- public/mix-manifest.json
- resources/assets/sass/component/_input.scss
> Review: fix-document-link-completion-logic-not-working

- app/Console/Commands/RefreshActivityElementCompleteness.php
- app/IATI/Data/elementJsonSchema.json
- app/IATI/Services/ElementCompleteService.php
- app/IATI/Services/ImportActivity/ImportXmlService.php
- resources/assets/js/views/activity/elements/Result.vue
- resources/assets/js/views/activity/indicators/IndicatorDetail.vue
- resources/assets/js/views/activity/results/ResultDetail.vue
- resources/assets/sass/component/_input.scss
- tests/Feature/Element/ResultCompleteTest.php
> Review: 1542-review-data-completeness-alert-for-activity-result-element

- app/IATI/API/CkanClient.php
> Review: 1570-remove-dataset_purge-and-use-package_delete

- app/IATI/Services/Activity/ActivityService.php
- app/IATI/Services/Activity/IndicatorService.php
- app/IATI/Services/Activity/PeriodService.php
- app/IATI/Services/Activity/ResultService.php
- app/IATI/Services/Activity/TransactionService.php
- app/Rules/RequiredEitherNumericTargetValueOrActualValue.php
- public/mix-manifest.json
> Review: 1566-check-xml-generation-code-for-unpopulated-sub-elements

- app/CsvImporter/Entities/Activity/Components/Factory/Validation.php
- app/Helpers/general.php
- app/Helpers/utils.php
- app/Http/Requests/Activity/ActivityBaseRequest.php
- app/Http/Requests/Activity/ParticipatingOrganization/ParticipatingOrganizationRequest.php
- app/IATI/Data/elementJsonSchema.json
- app/IATI/Elements/Forms/BaseForm.php
- app/IATI/Services/ElementCompleteService.php
- app/XlsImporter/Validator/Traits/RegistersValidationRules.php
- app/Xml/Validator/Traits/RegistersValidationRules.php
- app/XmlImporter/Foundation/Support/Factory/Validation.php
- config/laravel-form-builder.php
- resources/assets/sass/component/_forms.scss
- resources/assets/sass/component/_input.scss
- tests/Feature/Element/ParticipatingOrgCompleteTest.php
> Review: 1596-element-participating-org-requires-ref-or-sub-element-narrative-to-be-populated

- app/IATI/Data/elementJsonSchema.json
- public/js/script.js
- public/js/webportal-script.js
- public/manifest.js
> Review: 1595-review-recipient-country-and-recipient-region-percentage-labelling

- app/Http/Controllers/Admin/Workflow/BulkPublishingController.php
- public/css/app.css
- public/css/webportal-app.css
- public/mix-manifest.json
- resources/assets/sass/component/_input.scss
> Review: fix-core-elements-error-in-prod

- packages/production/config.yaml
> Review: update-config-prod

- app/CsvImporter/Entities/Activity/Components/ActivityRow.php
- app/CsvImporter/Queue/Jobs/ImportActivity.php
- app/Helpers/ImportCacheHelper.php
- app/Http/Controllers/Admin/ImportActivity/ImportActivityController.php
- app/Http/Controllers/Admin/ImportActivity/ImportXlsController.php
- app/IATI/Repositories/Import/ImportStatusRepository.php
- app/IATI/Services/ImportActivity/ImportStatusService.php
- app/IATI/Services/ImportActivity/ImportXlsService.php
- app/XlsImporter/Foundation/Mapper/Activity.php
- app/XlsImporter/Foundation/Mapper/Traits/XlsMapperHelper.php
- app/XlsImporter/Foundation/Mapper/XlsMapper.php
- app/XmlImporter/Foundation/Queue/ImportXml.php
- app/XmlImporter/Foundation/XmlQueueWriter.php
- resources/assets/js/views/activity/ActivityIndex.vue
- resources/assets/js/views/import/ActivityUpload.vue
- resources/assets/js/views/import/ActivityXlsUpload.vue
- resources/assets/js/views/import/ImportList.vue
- resources/assets/js/views/import/XlsList.vue
- routes/import.php
- tests/Unit/ImportXls/ImportActivityTest.php
> Review: 1604-troubleshoot-duplicate-activities-with-the-same-identifier

- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Requests/Web/IatiRegister/IatiRegisterFormRequest.php
- lang/en/register/iati_register_form_request.php
- lang/en/register/register_controller.php
- lang/en/validation.php
- lang/es/register/iati_register_form_request.php
- lang/es/register/register_controller.php
- lang/es/validation.php
- lang/fr/register/iati_register_form_request.php
- lang/fr/register/register_controller.php
- lang/fr/validation.php
- public/mix-manifest.json
- resources/assets/sass/component/_input.scss
> Review: 1653-register-module-register-type-2

- lang/en/footer/footer.php
- lang/es/footer/footer.php
- lang/footer/footer.php
- lang/fr/footer/footer.php
- public/mix-manifest.json
- resources/assets/js/views/web/partials/AdminFooter.vue
- resources/assets/js/views/web/partials/WebFooter.vue
> Review: 1658-admin-footer

- app/Http/Requests/Activity/Identifier/IdentifierRequest.php
> Translated validation for activity identifier request

- app/Http/Requests/Activity/Description/DescriptionRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> 1678 activity description request

- app/Http/Requests/Activity/OtherIdentifier/OtherIdentifierRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity other identifier request

- app/Http/Requests/Activity/Status/StatusRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity status request

- app/Http/Requests/Activity/Date/DateRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity date request

- app/Http/Requests/Activity/Scope/ScopeRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity scope request

- app/Http/Requests/Activity/RecipientRegion/RecipientRegionRequest.php
- lang/en/validation.php
> Translated validation for activity recipient region request

- app/Http/Requests/Activity/Sector/SectorRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity sector request

- app/Http/Requests/Activity/Tag/TagRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity tag request

- app/Http/Requests/Activity/PolicyMarker/PolicyMarkerRequest.php
- app/Http/Requests/Activity/Tag/TagRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity policy marker request

- app/Http/Requests/Activity/CollaborationType/CollaborationTypeRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity collaboration type request

- app/Http/Requests/Activity/DefaultAidType/DefaultAidTypeRequest.php
- app/Http/Requests/Activity/DefaultFinanceType/DefaultFinanceTypeRequest.php
- app/Http/Requests/Activity/DefaultFlowType/DefaultFlowTypeRequest.php
- app/Http/Requests/Activity/DefaultTiedStatus/DefaultTiedStatusRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
*[x] Translation for default flow type
*[x] Translation for default finance type
*[x] Translation for default aid type
*[x] Translation for default tied status
closes #1700 #1701 #1702 #1703
> 1700-activity-default-types

- app/Http/Requests/Activity/HumanitarianScope/HumanitarianScopeRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
> Translated validation for activity humanitarian scope request

- app/Http/Requests/Activity/Budget/BudgetRequest.php
- app/Http/Requests/Activity/Condition/ConditionRequest.php
- app/Http/Requests/Activity/ContactInfo/ContactInfoRequest.php
- app/Http/Requests/Activity/Location/LocationRequest.php
- app/Http/Requests/Activity/ParticipatingOrganization/ParticipatingOrganizationRequest.php
- app/Http/Requests/Activity/PlannedDisbursement/PlannedDisbursementRequest.php
- lang/en/validation.php
- lang/es/validation.php
- lang/fr/validation.php
*[x] Activity conditions
*[x] Actiivty legacy data
*[x] Activity document link
*[x] Activity contact info
*[x] Activity location
*[x] Activity planned disbursement
*[x] Activity participating org
*[x] Activity budget
> 1713-activity-conditions

- app/Http/Requests/Activity/Transaction/TransactionRequest.php
- app/Http/Requests/BulkDeleteTransactionRequest.php
- app/Rules/AlreadyInActivity.php
- lang/en/validation.php
- resources/assets/sass/component/_input.scss
> Translated validation for activity transaction request

- app/Http/Requests/Activity/Indicator/IndicatorRequest.php
- app/Http/Requests/Activity/Period/PeriodRequest.php
- app/Http/Requests/Activity/Result/ResultRequest.php
- app/Http/Requests/BulkDeleteResultRequest.php
- app/Rules/RequiredEitherNumericTargetValueOrActualValue.php
- lang/en/validation.php
> Translated validation for activity result, indicator, period requests

- app/Http/Requests/Activity/UploadActivity/ImportActivityRequest.php
- app/Http/Requests/Activity/UploadActivity/ImportXlsRequest.php
- lang/en/validation.php
> Translated validation for activity upload requests

- app/Http/Requests/Activity/Budget/BudgetRequest.php
- app/Http/Requests/Activity/PlannedDisbursement/PlannedDisbursementRequest.php
- app/Http/Requests/Activity/Transaction/TransactionRequest.php
- app/Http/Requests/Organization/DocumentLink/DocumentLinkRequest.php
- app/Http/Requests/Organization/Name/NameRequest.php
- app/Http/Requests/Organization/OrganizationBaseRequest.php
- app/Http/Requests/Organization/OrganizationIdentifier/OrganizationIdentifierRequest.php
- app/Http/Requests/Organization/RecipientCountryBudget/RecipientCountryBudgetRequest.php
- app/Http/Requests/Organization/RecipientOrgBudget/RecipientOrgBudgetRequest.php
- app/Http/Requests/Organization/RecipientRegionBudget/RecipientRegionBudgetRequest.php
- app/Http/Requests/Organization/ReportingOrg/ReportingOrgRequest.php
- app/Http/Requests/Organization/TotalBudget/TotalBudgetRequest.php
- app/Http/Requests/Organization/TotalExpenditure/TotalExpenditureRequest.php
- lang/en/validation.php
> Translated validation for organization requests

- app/Http/Requests/User/UserRequest.php
- app/Http/Requests/User/UserUpdateRequest.php
- lang/en/validation.php
> Translated validation for user requests

- README.md
- app/Console/Commands/ClearOlderAuditLogs.php
- app/Console/Commands/FetchOrganisationRegistrationAgency.php
- app/Console/Commands/FixPublishedXmlsForIssue1363Changes.php
- app/Console/Commands/Issue1419FillFullnameAndEmailInAuditLog.php
- app/Console/Commands/Issue1419HardDeleteSoftDeletedUsers.php
- app/Console/Commands/SetAppDataJsonCache.php
- app/IATI/Repositories/Activity/ValidationStatusRepository.php
- app/IATI/Services/Xml/XmlGeneratorService.php
- app/Rules/RequiredEitherNumericTargetValueOrActualValue.php
- database/factories/IATI/Models/Activity/TransactionFactory.php
- database/migrations/2024_07_22_091222_update_email_collation_in_users_table.php
- packages/base/cron/clear-laravel-logs.yaml
- packages/base/cron/cronjob.yaml
- packages/base/cron/custom-command-cron.yaml
- packages/base/cron/fix-storage-permission.yaml
- packages/base/fpm/deployment.yaml
- packages/base/queue-workers/deployment.yaml
- packages/base/webserver/deployment.yaml
- packages/development/kustomization.yaml
- packages/production/kustomization.yaml
- packages/staging/kustomization.yaml
- tests/Feature/Element/PolicyMarkerCompleteTest.php
- tests/Feature/Element/ResultCompleteTest.php
- tests/Unit/Csv/BudgetCsvTest.php
- tests/Unit/TestFiles/Xml/complete.xml
- tests/Unit/Xml/BudgetXmlTest.php
I have done the following tasks:
If everything is alright, we can test things on our development website and finalise them on the staging website.
> Review: 1741-post-migration-update-of-git-remotes-in-repository

- .github/workflows/development-workflow.yml
- .github/workflows/production-workflow.yml
- .github/workflows/staging-workflow.yml
- README.md
- app/Console/Commands/ClearOlderAuditLogs.php
- app/Console/Commands/FetchOrganisationRegistrationAgency.php
- app/Console/Commands/FixPublishedXmlsForIssue1363Changes.php
- app/Console/Commands/Issue1419FillFullnameAndEmailInAuditLog.php
- app/Console/Commands/Issue1419HardDeleteSoftDeletedUsers.php
- app/Console/Commands/SetAppDataJsonCache.php
- app/IATI/Repositories/Activity/ValidationStatusRepository.php
- app/IATI/Services/Xml/XmlGeneratorService.php
- app/Rules/RequiredEitherNumericTargetValueOrActualValue.php
- database/factories/IATI/Models/Activity/TransactionFactory.php
- database/migrations/2024_07_22_091222_update_email_collation_in_users_table.php
- packages/base/cron/clear-laravel-logs.yaml
- packages/base/cron/cronjob.yaml
- packages/base/cron/custom-command-cron.yaml
- packages/base/cron/fix-storage-permission.yaml
- packages/base/fpm/deployment.yaml
- packages/base/queue-workers/deployment.yaml
- packages/base/webserver/deployment.yaml
- packages/development/kustomization.yaml
- packages/production/kustomization.yaml
- packages/staging/kustomization.yaml
- tests/Feature/Element/PolicyMarkerCompleteTest.php
- tests/Feature/Element/ResultCompleteTest.php
- tests/Unit/Csv/BudgetCsvTest.php
- tests/Unit/TestFiles/Xml/complete.xml
- tests/Unit/Xml/BudgetXmlTest.php
> Review: Hotfix of image name on github workflow files.

- resources/assets/js/components/BulkPublishRevalidatePopup.vue
- resources/assets/sass/component/_input.scss
> Review: main-fix-deploy

- resources/assets/sass/component/_forms.scss
> Review: 1736-formbuilder-issue---border-expanding-on-collapsable-elements

- app/Helpers/general.php
- app/IATI/Services/Activity/ActivityService.php
- resources/assets/js/views/activity/ActivityDetail.vue
- resources/assets/js/views/organisation/OrganisationData.vue
- resources/views/admin/organisation/index.blade.php
> Review: 1633-organisation-data-publishing-progress-depends-on-more-than-core-elements

- config/queue.php
> Review: 1755-increase-queue-timeout

- app/Http/Controllers/Admin/Organization/OrganizationIdentifierController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/IATI/Services/Organization/OrganizationService.php
- app/IATI/Services/Setting/SettingService.php
- app/IATI/Services/User/UserService.php
- app/IATI/Traits/MigrateSettingTrait.php
- app/IATI/Traits/RegistryApiInvoker.php
> Review: 1757-get-request-sets-user-agent-guzzle

- app/Http/Controllers/Admin/Download/DownloadActivityController.php
- resources/assets/js/views/activity/partials/DownloadActivityButton.vue
> Review: 1573-remove-xml-download-error-warning

- app/XmlImporter/Foundation/Queue/ImportXml.php
- app/XmlImporter/Foundation/Support/Helpers/Traits/XmlHelper.php
- app/XmlImporter/Foundation/XmlQueueProcessor.php
> Review: 1760-location-element-latitude-and-longitude-not-populated-during-xml-import

- resources/assets/sass/component/_input.scss
- routes/web.php
> Review: 1783-redeploy-prod

- packages/production/config.yaml
-[x] Update default bucket region on production
> Review: 1785-update-default-bucket-region-on-production

- app/Http/Controllers/Admin/Workflow/BulkPublishingController.php
- public/mix-manifest.json
- resources/assets/sass/component/_input.scss
> Review: 1794-redeploy-main

- .github/workflows/development-workflow.yml
- .github/workflows/production-workflow.yml
- .github/workflows/staging-workflow.yml
Revert "Merge pull request #1773 from IATI/dependabot/github_actions/docker/login-action-3.4.0"
This reverts commit 6401a291f0f97132d98c2f405a45bd182c953a13, reversing changes made to 00cfc6edb7d0a0e9353759e930c2ec3a00c2d3d3.
> Review: 1796-close-all-open-prs-and-implement-security-patches

- resources/assets/js/views/activity/ActivityDetail.vue
- tests/Feature/RegisterTest.php
> Review: 1840-revert-sidebar-changes

- app/Http/Controllers/Admin/ImportActivity/ImportActivityController.php
- app/IATI/Traits/HydrationTrait.php
- app/XlsImporter/Foundation/Mapper/Activity.php
- app/XmlImporter/Foundation/Mapper/Components/XmlMapper.php
- resources/assets/js/views/import/ImportList.vue
- resources/assets/js/views/import/XlsList.vue
- resources/assets/sass/component/_input.scss
> Review: 1834-check-activity-transaction-element-data-completeness-after-xml-import
